#!/bin/bash

set -eo pipefail

[[ -z "$DEBUG" ]] || set -x

ABCON_PACKAGE="${ABCON_PACKAGE:-abcon}"
ABCON_DOCKER="${ABCON_DOCKER:-airbyte/abcon-cli}"

VENV_PATH=${VENV_PATH:-.venv}

PYTHON_DEFAULT=$(which python || which python3)
PYTHON_CMD="${PYTHON_CMD:-${PYTHON_DEFAULT}}"

_error() {
    echo "$@" 1>&2 && exit 1
}

_setup_env() {
    if [[ ! -d "${VENV_PATH}" ]]; then
      "${PYTHON_CMD}" -m venv "${VENV_PATH}"
      source "${VENV_PATH}/bin/activate"

      pip install --upgrade pip
      pip install -e "${ABCON_PACKAGE}"
    else
      source "${VENV_PATH}/bin/activate"
    fi

}

main() {
    if [[ -z "$USE_ABCON_DOCKER" ]]; then
      _setup_env
      abcon-cli "$@"
    else
      docker run --rm -v $(pwd):/stage "$ABCON_DOCKER" "$@"
    fi
}

main "$@"
