#!/bin/bash

set -eo pipefail

[[ -z "$INK_DEBUG" ]] || set -x

INK_PACKAGE="${INK_PACKAGE:-ink}"
INK_IMAGE="${INK_IMAGE:-airbyte/ink}"

INK_VENV_PATH=${INK_VENV_PATH:-.venv}

PYTHON_DEFAULT=$(which python || which python3)
PYTHON_CMD="${PYTHON_CMD:-${PYTHON_DEFAULT}}"

_error() {
    echo "$@" 1>&2 && exit 1
}

_setup_env() {
    if [[ ! -d "${INK_VENV_PATH}" ]]; then
      "${PYTHON_CMD}" -m venv "${INK_VENV_PATH}"
      source "${INK_VENV_PATH}/bin/activate"

      pip install --upgrade pip
      pip install -e "${INK_PACKAGE}"
    else
      source "${INK_VENV_PATH}/bin/activate"
    fi

}

main() {
    if [[ -z "$INK_USE_DOCKER" ]]; then
      _setup_env
      ink "$@"
    else
      docker run --rm -v $(pwd):/stage -e INK_IN_DOCKER=1 "$INK_IMAGE" "$@"
    fi
}

main "$@"
