#!/bin/bash

set -eo pipefail

[[ -z "$DEBUG" ]] || set -x

INK_PACKAGE="${INK_PACKAGE:-ink}"
INK_DOCKER="${INK_DOCKER:-airbyte/ink}"

VENV_PATH=${VENV_PATH:-.venv}

PYTHON_DEFAULT=$(which python || which python3)
PYTHON_CMD="${PYTHON_CMD:-${PYTHON_DEFAULT}}"

_error() {
    echo "$@" 1>&2 && exit 1
}

_setup_env() {
    if [[ ! -d "${VENV_PATH}" ]]; then
      "${PYTHON_CMD}" -m venv "${VENV_PATH}"
      source "${VENV_PATH}/bin/activate"

      pip install --upgrade pip
      pip install -e "${INK_PACKAGE}"
    else
      source "${VENV_PATH}/bin/activate"
    fi

}

main() {
    if [[ -z "$USE_INK_DOCKER" ]]; then
      _setup_env
      ink "$@"
    else
      docker run --rm -v $(pwd):/stage "$INK_DOCKER" "$@"
    fi
}

main "$@"
