#!/bin/bash

set -eo pipefail

set -a
ENV_PATH=${ENV_PATH:-.env}
[[ -f "${ENV_PATH}" ]] && source "${ENV_PATH}"
set +a

[[ -z "$DEBUG" ]] || set -x

DEV_VERSION=${DEV_VERSION:-latest}
ABCON_URL=${ABCON_URL:-https://tools.airbyte.com/${DEV_VERSION}/abcon}

BUILD_DIR="build"
ABCON_CMD="$BUILD_DIR/_abcon"

_error() {
    echo "$@" 1>&2 && exit 1
}

_download_con() {
    mkdir -p $BUILD_DIR
    curl -fsSL "$ABCON_URL" -o "${ABCON_CMD}" || _error "Invalid URL: ${ABCON_URL}"
    chmod +x "${ABCON_CMD}"
    echo "Upgraded ($ABCON_URL)"
}

main() {
    [[ -f "${ABCON_CMD}" && -z "$ABCON_UPGRADE" ]] || _download_con 1>&2

    "${ABCON_CMD}" "$@"
}

main "$@"
