[tool.poetry]
name = "abcon"
version = "0.1.0"
description = "Connector management CLI"
authors = ["Michel Tricot <michel@airbyte.io>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
