name: release

on:
  push:
    tags:
      - '*.*.*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install Poetry
        run: pip install poetry

      - name: Build project for distribution
        run: poetry build

#      - name: Docker meta
#        id: meta
#        uses: docker/metadata-action@v4
#        with:
#          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Log in to the Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GITHUB }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          build-args: PYTHON_VERSION=3.9.0

#      - name: Create Docker image
#        run: |
#          docker build . -t ink:$(poetry version -s) --build-arg PYTHON_VERSION=$(cat .python-version)
#          docker build . -t ink --build-arg PYTHON_VERSION=$(cat .python-version)
#
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*,ink,_ink"
          draft: false
          prerelease: false
#
#      - name: Publish to PyPI
#        env:
#          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
#        run: poetry publish
